apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: le-az-http-certissuer-prod
  name: waha-claude-ingress
  namespace: waha-claude-prod
spec:
  ingressClassName: traefik
  rules:
    - host: waha-claude.limechat.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: waha-claude-service
                port:
                  number: 8080
  tls:
    - hosts:
        - waha-claude.limechat.ai
      secretName: tls-waha-claude-ingress
